---
version: '3.8'

services:
  haproxy:
    container_name: haproxy
    image: haproxy:2.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - node
      - backend
      - database
    networks:
      - local

  node:
    container_name: node
    build: ./docker/node/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/app
    tty: true
    networks:
      - local

  backend:
    container_name: backend
    build: ./docker/php
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
    tty: true
    networks:
      - local

  database:
    container_name: database
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: local
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge