import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Home from "@/app/page";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rico\'s simple TODO app",
  description: "Generated by the beautiful next shizzle",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={outfit.className}>
        <Home/>
    </body>
    </html>
  );
}
